---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance1
    image: docker.io/centos:7
    pre_build_image: true
    privileged: True
    command: /sbin/init
  - name: instance2
    image: docker.io/centos:8
    pre_build_image: true
    privileged: True
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible
